<html> <h1 style="font-style:bold; color:blue;"> Machine Learning in Finance </h1> </html>

<html> <h1 style="font-style:italic; color:blue;"> Week-2 </h1> </html>

# Python Data Analysis Library

### Pandas is an open source library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language

![image.png]()

![image.png]()

In [1]:
!cat /proc/driver/nvidia/gpus/0000:00:04.0/information

Model: 		 Unknown
IRQ:   		 11
GPU UUID: 	 GPU-c7ab3b8b-f1b6-a627-03aa-2aa79a5195cc
Video BIOS: 	 90.04.a7.00.01
Bus Type: 	 PCI
DMA Size: 	 47 bits
DMA Mask: 	 0x7fffffffffff
Bus Location: 	 0000:00:04.0
Device Minor: 	 0
GPU Excluded:	 No

................................![image.png]()

In [2]:
from google.colab import files
uploaded = files.upload()

Saving adult_data_mini.csv to adult_data_mini.csv

## Data Frame

...............................![image.png]()

In [3]:
ls

adult_data_mini.csv  sample_data/

'adult_data_mini (1).csv'   adult_data_mini.csv   sample_data/

.........................................![image.png]()

In [4]:
import  pandas as pd

.........................................![image.png]()

In [5]:
df = pd.DataFrame({'numbers':range(8), 'chars':['g']*8})

.........................................![image.png]()

In [6]:
df

   numbers chars
0        0     g
1        1     g
2        2     g
3        3     g
4        4     g
5        5     g
6        6     g
7        7     g

   numbers chars
0        0     g
1        1     g
2        2     g
3        3     g
4        4     g
5        5     g
6        6     g
7        7     g

.........................................![image.png]()

In [7]:
df=[]
df

[]

[]

.........................................![image.png]()

In [8]:
data = pd.read_csv('adult_data_mini.csv',header =0)
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,NaN,NaN,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,NaN,NaN,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,NaN,0.0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178.0,NaN,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,NaN,NaN,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,NaN,0.0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,NaN,NaN,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,NaN,NaN,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,NaN,NaN,40,?,>50K

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,NaN,NaN,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,NaN,NaN,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,NaN,0.0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178.0,NaN,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,NaN,NaN,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,NaN,0.0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,NaN,NaN,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,NaN,NaN,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,NaN,NaN,40,?,>50K

.........................................![image.png]()

In [10]:
data.shape

(15, 15)

(15, 15)

.........................................![image.png]()

In [11]:
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,NaN,NaN,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,NaN,NaN,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40,Cuba,<=50K

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,NaN,NaN,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,NaN,NaN,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40,Cuba,<=50K

<html> <h3 style="color:blue;"> DataFrame Modification </h3> </html>

.........................................![image.png]()

In [12]:
New_Line = {'age': '25','Workclass':'Private','education':'Some-college','race':'White','sex':'Male'}
print(New_Line)
print(type(New_Line))

{'age': '25', 'Workclass': 'Private', 'education': 'Some-college', 'race': 'White', 'sex': 'Male'}
<class 'dict'>

{'age': '25', 'workclass': 'Private', 'education': 'Some-college', 'race': 'White', 'sex': 'Male'}
<class 'dict'>

.........................................![image.png]()

In [13]:
New_Line_series = pd.Series(New_Line)
print(type(New_Line_series))
print(New_Line_series, '\n')
New_Line_dataframe = New_Line_series.to_frame().T
print(type(New_Line_dataframe))
New_Line_dataframe

<class 'pandas.core.series.Series'>
age                    25
Workclass         Private
education    Some-college
race                White
sex                  Male
dtype: object

<class 'pandas.core.frame.DataFrame'>

  age Workclass     education   race   sex
0  25   Private  Some-college  White  Male

<class 'pandas.core.series.Series'>
age                    25
workclass         Private
education    Some-college
race                White
sex                  Male
dtype: object

<class 'pandas.core.frame.DataFrame'>

  age workclass     education   race   sex
0  25   Private  Some-college  White  Male

.........................................![image.png]()

In [14]:
data = pd.concat([data,New_Line_dataframe], ignore_index=True)
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,Workclass
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K,NaN
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,13.0,United-States,<=50K,NaN
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,NaN,NaN,40.0,United-States,<=50K,NaN
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,NaN,NaN,40.0,United-States,<=50K,NaN
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40.0,Cuba,<=50K,NaN
5,37,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40.0,United-States,<=50K,NaN
6,49,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,NaN,0.0,16.0,Jamaica,<=50K,NaN
7,52,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,45.0,United-States,>50K,NaN
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,NaN
9,42,Private,159449.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178.0,NaN,40.0,United-States,>50K,NaN
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,NaN,NaN,80.0,United-States,>50K,NaN
11,30,State-gov,141297.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,NaN,0.0,40.0,India,>50K,NaN
12,23,Private,122272.0,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,NaN,NaN,30.0,United-States,<=50K,NaN
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,NaN,NaN,50.0,United-States,<=50K,NaN
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,NaN,NaN,40.0,?,>50K,NaN
15,25,NaN,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,NaN,NaN,NaN,NaN,NaN,Private

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,13.0,United-States,<=50K
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,NaN,NaN,40.0,United-States,<=50K
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,NaN,NaN,40.0,United-States,<=50K
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40.0,Cuba,<=50K
5,37,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40.0,United-States,<=50K
6,49,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,NaN,0.0,16.0,Jamaica,<=50K
7,52,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,45.0,United-States,>50K
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K
9,42,Private,159449.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178.0,NaN,40.0,United-States,>50K
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,NaN,NaN,80.0,United-States,>50K
11,30,State-gov,141297.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,NaN,0.0,40.0,India,>50K
12,23,Private,122272.0,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,NaN,NaN,30.0,United-States,<=50K
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,NaN,NaN,50.0,United-States,<=50K
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,NaN,NaN,40.0,?,>50K
15,25,Private,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,NaN,NaN,NaN,NaN,NaN

In [ ]:
# If you use the default value
# ignore_index=False,
# then the row index at the end will be -0-

.........................................![image.png]()

In [15]:
data.drop([9,11], axis=0, inplace=True)
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,Workclass
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K,NaN
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,13.0,United-States,<=50K,NaN
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,NaN,NaN,40.0,United-States,<=50K,NaN
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,NaN,NaN,40.0,United-States,<=50K,NaN
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40.0,Cuba,<=50K,NaN
5,37,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40.0,United-States,<=50K,NaN
6,49,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,NaN,0.0,16.0,Jamaica,<=50K,NaN
7,52,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,45.0,United-States,>50K,NaN
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,NaN
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,NaN,NaN,80.0,United-States,>50K,NaN
12,23,Private,122272.0,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,NaN,NaN,30.0,United-States,<=50K,NaN
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,NaN,NaN,50.0,United-States,<=50K,NaN
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,NaN,NaN,40.0,?,>50K,NaN
15,25,NaN,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,NaN,NaN,NaN,NaN,NaN,Private

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,13.0,United-States,<=50K
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,NaN,NaN,40.0,United-States,<=50K
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,NaN,NaN,40.0,United-States,<=50K
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40.0,Cuba,<=50K
5,37,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40.0,United-States,<=50K
6,49,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,NaN,0.0,16.0,Jamaica,<=50K
7,52,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,45.0,United-States,>50K
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,NaN,NaN,80.0,United-States,>50K
12,23,Private,122272.0,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,NaN,NaN,30.0,United-States,<=50K
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,NaN,NaN,50.0,United-States,<=50K
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,NaN,NaN,40.0,?,>50K
15,25,Private,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,NaN,NaN,NaN,NaN,NaN

.........................................![image.png]()

In [16]:
data['IsHomeless'] = [False]*13 +[True]
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,Workclass,IsHomeless
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K,NaN,False
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,13.0,United-States,<=50K,NaN,False
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,NaN,NaN,40.0,United-States,<=50K,NaN,False
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,NaN,NaN,40.0,United-States,<=50K,NaN,False
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40.0,Cuba,<=50K,NaN,False
5,37,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40.0,United-States,<=50K,NaN,False
6,49,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,NaN,0.0,16.0,Jamaica,<=50K,NaN,False
7,52,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,45.0,United-States,>50K,NaN,False
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,NaN,False
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,NaN,NaN,80.0,United-States,>50K,NaN,False
12,23,Private,122272.0,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,NaN,NaN,30.0,United-States,<=50K,NaN,False
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,NaN,NaN,50.0,United-States,<=50K,NaN,False
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,NaN,NaN,40.0,?,>50K,NaN,False
15,25,NaN,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,NaN,NaN,NaN,NaN,NaN,Private,True

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,IsHomeless
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K,False
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,13.0,United-States,<=50K,False
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,NaN,NaN,40.0,United-States,<=50K,False
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,NaN,NaN,40.0,United-States,<=50K,False
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40.0,Cuba,<=50K,False
5,37,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40.0,United-States,<=50K,False
6,49,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,NaN,0.0,16.0,Jamaica,<=50K,False
7,52,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,0.0,45.0,United-States,>50K,False
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,False
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,NaN,NaN,80.0,United-States,>50K,False
12,23,Private,122272.0,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,NaN,NaN,30.0,United-States,<=50K,False
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,NaN,NaN,50.0,United-States,<=50K,False
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,NaN,NaN,40.0,?,>50K,False
15,25,Private,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,NaN,NaN,NaN,NaN,NaN,True

.........................................![image.png]()

In [17]:
data.shape

(14, 17)

(14, 16)

.........................................![image.png]()

In [18]:
data.dtypes

age                object
workclass          object
fnlwgt            float64
education          object
education-num     float64
marital-status     object
occupation         object
relationship       object
race               object
sex                object
capital-gain      float64
capital-loss      float64
hours-per-week    float64
native-country     object
 Answer            object
Workclass          object
IsHomeless           bool
dtype: object

age                object
workclass          object
fnlwgt            float64
education          object
education-num     float64
marital-status     object
occupation         object
relationship       object
race               object
sex                object
capital-gain      float64
capital-loss      float64
hours-per-week    float64
native-country     object
 Answer            object
IsHomeless           bool
dtype: object

.........................................![image.png]()

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 15
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             14 non-null     object
 1   workclass       13 non-null     object
 2   fnlwgt          13 non-null     float64
 3   education       14 non-null     object
 4   education-num   13 non-null     float64
 5   marital-status  13 non-null     object
 6   occupation      13 non-null     object
 7   relationship    13 non-null     object
 8   race            14 non-null     object
 9   sex             14 non-null     object
 10  capital-gain    4 non-null      float64
 11  capital-loss    3 non-null      float64
 12  hours-per-week  13 non-null     float64
 13  native-country  13 non-null     object
 14   Answer         13 non-null     object
 15  Workclass       1 non-null      object
 16  IsHomeless      14 non-null     bool
dtypes: bool(1), float64(5), object(11)
memory usage: 1.9+ KB

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 0 to 15
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             14 non-null     object
 1   workclass       14 non-null     object
 2   fnlwgt          13 non-null     float64
 3   education       14 non-null     object
 4   education-num   13 non-null     float64
 5   marital-status  13 non-null     object
 6   occupation      13 non-null     object
 7   relationship    13 non-null     object
 8   race            14 non-null     object
 9   sex             14 non-null     object
 10  capital-gain    4 non-null      float64
 11  capital-loss    3 non-null      float64
 12  hours-per-week  13 non-null     float64
 13  native-country  13 non-null     object
 14   Answer         13 non-null     object
 15  IsHomeless      14 non-null     bool
dtypes: bool(1), float64(5), object(10)
memory usage: 1.8+ KB

<html> <h3 style="color:blue;"> Missing Data </h3> </html>

.........................................![image.png]()

In [20]:
data['capital-gain'] = data['capital-gain'].fillna(0)
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,Workclass,IsHomeless
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K,NaN,False
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K,NaN,False
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,NaN,40.0,United-States,<=50K,NaN,False
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,NaN,40.0,United-States,<=50K,NaN,False
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40.0,Cuba,<=50K,NaN,False
5,37,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40.0,United-States,<=50K,NaN,False
6,49,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0.0,0.0,16.0,Jamaica,<=50K,NaN,False
7,52,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,45.0,United-States,>50K,NaN,False
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,NaN,False
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0.0,NaN,80.0,United-States,>50K,NaN,False
12,23,Private,122272.0,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,0.0,NaN,30.0,United-States,<=50K,NaN,False
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,NaN,False
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0.0,NaN,40.0,?,>50K,NaN,False
15,25,NaN,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,0.0,NaN,NaN,NaN,NaN,Private,True

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,IsHomeless
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K,False
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K,False
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,NaN,40.0,United-States,<=50K,False
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,NaN,40.0,United-States,<=50K,False
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40.0,Cuba,<=50K,False
5,37,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40.0,United-States,<=50K,False
6,49,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0.0,0.0,16.0,Jamaica,<=50K,False
7,52,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,45.0,United-States,>50K,False
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,False
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0.0,NaN,80.0,United-States,>50K,False
12,23,Private,122272.0,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,0.0,NaN,30.0,United-States,<=50K,False
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,False
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0.0,NaN,40.0,?,>50K,False
15,25,Private,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,0.0,NaN,NaN,NaN,NaN,True

<html> <h3 style="color:blue;"> Data slice manipulating </h3> </html>

.........................................![image.png]()

In [21]:
data.education

0         Bachelors
1         Bachelors
2           HS-grad
3              11th
4         Bachelors
5           Masters
6               9th
7           HS-grad
8           Masters
10     Some-college
12        Bachelors
13       Assoc-acdm
14        Assoc-voc
15     Some-college
Name: education, dtype: object

0         Bachelors
1         Bachelors
2           HS-grad
3              11th
4         Bachelors
5           Masters
6               9th
7           HS-grad
8           Masters
10     Some-college
12        Bachelors
13       Assoc-acdm
14        Assoc-voc
15     Some-college
Name: education, dtype: object

.........................................![image.png]()

In [22]:
data['capital-gain']

0      2174.0
1         0.0
2         0.0
3         0.0
4         0.0
5         0.0
6         0.0
7         0.0
8     14084.0
10        0.0
12        0.0
13        0.0
14        0.0
15        0.0
Name: capital-gain, dtype: float64

0      2174.0
1         0.0
2         0.0
3         0.0
4         0.0
5         0.0
6         0.0
7         0.0
8     14084.0
10        0.0
12        0.0
13        0.0
14        0.0
15        0.0
Name: capital-gain, dtype: float64

.........................................![image.png]()

In [23]:
data[['capital-gain']]

    capital-gain
0         2174.0
1            0.0
2            0.0
3            0.0
4            0.0
5            0.0
6            0.0
7            0.0
8        14084.0
10           0.0
12           0.0
13           0.0
14           0.0
15           0.0

    capital-gain
0         2174.0
1            0.0
2            0.0
3            0.0
4            0.0
5            0.0
6            0.0
7            0.0
8        14084.0
10           0.0
12           0.0
13           0.0
14           0.0
15           0.0

.........................................![image.png]()

In [24]:
data[['occupation','capital-gain']]

            occupation  capital-gain
0         Adm-clerical        2174.0
1      Exec-managerial           0.0
2    Handlers-cleaners           0.0
3    Handlers-cleaners           0.0
4       Prof-specialty           0.0
5      Exec-managerial           0.0
6        Other-service           0.0
7      Exec-managerial           0.0
8       Prof-specialty       14084.0
10     Exec-managerial           0.0
12        Adm-clerical           0.0
13               Sales           0.0
14        Craft-repair           0.0
15                 NaN           0.0

            occupation  capital-gain
0         Adm-clerical        2174.0
1      Exec-managerial           0.0
2    Handlers-cleaners           0.0
3    Handlers-cleaners           0.0
4       Prof-specialty           0.0
5      Exec-managerial           0.0
6        Other-service           0.0
7      Exec-managerial           0.0
8       Prof-specialty       14084.0
10     Exec-managerial           0.0
12        Adm-clerical           0.0
13               Sales           0.0
14        Craft-repair           0.0
15                 NaN           0.0

.........................................![image.png]()

In [25]:
data[:3]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,Workclass,IsHomeless
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K,NaN,False
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K,NaN,False
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,NaN,40.0,United-States,<=50K,NaN,False

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,IsHomeless
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K,False
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K,False
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,NaN,40.0,United-States,<=50K,False

.........................................![image.png]()

In [26]:
data[-3:]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,Workclass,IsHomeless
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,NaN,False
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0.0,NaN,40.0,?,>50K,NaN,False
15,25,NaN,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,0.0,NaN,NaN,NaN,NaN,Private,True

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,IsHomeless
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,False
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0.0,NaN,40.0,?,>50K,False
15,25,Private,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,0.0,NaN,NaN,NaN,NaN,True

.........................................![image.png]()

In [27]:
data.tail(3)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,Workclass,IsHomeless
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,NaN,False
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0.0,NaN,40.0,?,>50K,NaN,False
15,25,NaN,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,0.0,NaN,NaN,NaN,NaN,Private,True

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,IsHomeless
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,False
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0.0,NaN,40.0,?,>50K,False
15,25,Private,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,0.0,NaN,NaN,NaN,NaN,True

.........................................![image.png]()

In [28]:
data.loc[[0,1,2], ["education", "occupation"]]

    education          occupation
0   Bachelors        Adm-clerical
1   Bachelors     Exec-managerial
2     HS-grad   Handlers-cleaners

    education          occupation
0   Bachelors        Adm-clerical
1   Bachelors     Exec-managerial
2     HS-grad   Handlers-cleaners

.........................................![image.png]()

In [29]:
data.iloc[[1,2,5],[0,3]]

  age   education
1  50   Bachelors
2  38     HS-grad
5  37     Masters

  age   education
1  50   Bachelors
2  38     HS-grad
5  37     Masters

.........................................![image.png]()

In [30]:
data['education'].loc[2]

' HS-grad'

' HS-grad'

.........................................![image.png]()

In [31]:
data.iloc[7]

age                                52
workclass            Self-emp-not-inc
fnlwgt                       209642.0
education                     HS-grad
education-num                     9.0
marital-status     Married-civ-spouse
occupation            Exec-managerial
relationship                  Husband
race                            White
sex                              Male
capital-gain                      0.0
capital-loss                      0.0
hours-per-week                   45.0
native-country          United-States
 Answer                          >50K
Workclass                         NaN
IsHomeless                      False
Name: 7, dtype: object

age                                52
workclass            Self-emp-not-inc
fnlwgt                       209642.0
education                     HS-grad
education-num                     9.0
marital-status     Married-civ-spouse
occupation            Exec-managerial
relationship                  Husband
race                            White
sex                              Male
capital-gain                      0.0
capital-loss                      0.0
hours-per-week                   45.0
native-country          United-States
 Answer                          >50K
IsHomeless                      False
Name: 7, dtype: object

<html> <h3 style="color:blue;"> Selection with conditions </h3> </html>

.........................................![image.png]()

In [32]:
data[data['hours-per-week'] >= 50]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,Workclass,IsHomeless
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,NaN,False
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0.0,NaN,80.0,United-States,>50K,NaN,False
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,NaN,False

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,IsHomeless
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,False
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0.0,NaN,80.0,United-States,>50K,False
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,False

.........................................![image.png]()

In [33]:
data[(data['hours-per-week'] >= 50) & (data ['education-num'] > 11)]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,Workclass,IsHomeless
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,NaN,False
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,NaN,False

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,IsHomeless
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,False
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,False

.........................................![image.png]()

In [34]:
data[(data['hours-per-week'] >= 50) | (data.IsHomeless == True)]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,Workclass,IsHomeless
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,NaN,False
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0.0,NaN,80.0,United-States,>50K,NaN,False
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,NaN,False
15,25,NaN,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,0.0,NaN,NaN,NaN,NaN,Private,True

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,IsHomeless
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,False
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0.0,NaN,80.0,United-States,>50K,False
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,False
15,25,Private,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,0.0,NaN,NaN,NaN,NaN,True

.........................................![image.png]()

In [35]:
data.loc[[7,8],['education','occupation']]

  education        occupation
7   HS-grad   Exec-managerial
8   Masters    Prof-specialty

  education        occupation
7   HS-grad   Exec-managerial
8   Masters    Prof-specialty

.........................................![image.png]()

In [36]:
data['native-country'].unique()

array([' United-States', ' Cuba', ' Jamaica', ' ?', nan], dtype=object)

array([' United-States', ' Cuba', ' Jamaica', ' ?', nan], dtype=object)

.........................................![image.png]()

In [37]:
data['native-country'].value_counts()

native-country
United-States    10
Cuba              1
Jamaica           1
?                 1
Name: count, dtype: int64

native-country
United-States    10
Cuba              1
Jamaica           1
?                 1
Name: count, dtype: int64

.........................................![image.png]()

In [38]:
data['education'].apply(len)

0     10
1     10
2      8
3      5
4     10
5      8
6      4
7      8
8      8
10    13
12    10
13    11
14    10
15    12
Name: education, dtype: int64

0     10
1     10
2      8
3      5
4     10
5      8
6      4
7      8
8      8
10    13
12    10
13    11
14    10
15    12
Name: education, dtype: int64

In [ ]:
# Analyse the result above!

# Write your ideas about why more characters are counted in some rows

.........................................![image.png]()

In [40]:
data.sort_values(by='hours-per-week', ascending=False)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,Workclass,IsHomeless
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0.0,NaN,80.0,United-States,>50K,NaN,False
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,NaN,False
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,NaN,False
7,52,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,45.0,United-States,>50K,NaN,False
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K,NaN,False
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0.0,NaN,40.0,?,>50K,NaN,False
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40.0,Cuba,<=50K,NaN,False
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,NaN,40.0,United-States,<=50K,NaN,False
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,NaN,40.0,United-States,<=50K,NaN,False
5,37,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40.0,United-States,<=50K,NaN,False
12,23,Private,122272.0,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,0.0,NaN,30.0,United-States,<=50K,NaN,False
6,49,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0.0,0.0,16.0,Jamaica,<=50K,NaN,False
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K,NaN,False
15,25,NaN,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,0.0,NaN,NaN,NaN,NaN,Private,True

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,IsHomeless
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0.0,NaN,80.0,United-States,>50K,False
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,False
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,False
7,52,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,45.0,United-States,>50K,False
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K,False
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0.0,NaN,40.0,?,>50K,False
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40.0,Cuba,<=50K,False
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,NaN,40.0,United-States,<=50K,False
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,NaN,40.0,United-States,<=50K,False
5,37,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40.0,United-States,<=50K,False
12,23,Private,122272.0,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,0.0,NaN,30.0,United-States,<=50K,False
6,49,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0.0,0.0,16.0,Jamaica,<=50K,False
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K,False
15,25,Private,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,0.0,NaN,NaN,NaN,NaN,True

<html> <h3 style="color:blue;"> Grouping </h3> </html>

In [ ]:
# groupby() - the function groups the first column based on the second


.........................................![image.png]()

In [41]:
Group_by_education = data.groupby(["sex","education"])
Group_by_education.size()

sex      education
 Female   9th             1
          Bachelors       2
          Masters         2
 Male     11th            1
          Assoc-acdm      1
          Assoc-voc       1
          Bachelors       2
          HS-grad         2
          Some-college    1
Male     Some-college     1
dtype: int64

sex      education
 Female   9th             1
          Bachelors       2
          Masters         2
 Male     11th            1
          Assoc-acdm      1
          Assoc-voc       1
          Bachelors       2
          HS-grad         2
          Some-college    1
Male     Some-college     1
dtype: int64

In [ ]:
# As you see above, the string variables were not grouped correctly as they have some spaces.

.........................................![image.png]()

In [44]:
data["sex"] = data["sex"].map(str.strip)
Group_by_education = data.groupby(["sex","education"])
Group_by_education.size()

sex     education
Female   9th             1
         Bachelors       2
         Masters         2
Male     11th            1
         Assoc-acdm      1
         Assoc-voc       1
         Bachelors       2
         HS-grad         2
         Some-college    1
        Some-college     1
dtype: int64

sex     education
Female   9th             1
         Bachelors       2
         Masters         2
Male     11th            1
         Assoc-acdm      1
         Assoc-voc       1
         Bachelors       2
         HS-grad         2
         Some-college    1
        Some-college     1
dtype: int64

In [ ]:
# The 'education' colomn also has data with spaces

.........................................![image.png]()

In [45]:
data["education"] = data["education"].map(str.strip)
Group_by_education = data.groupby(["sex","education"])
Group_by_education.size()

sex     education
Female  9th             1
        Bachelors       2
        Masters         2
Male    11th            1
        Assoc-acdm      1
        Assoc-voc       1
        Bachelors       2
        HS-grad         2
        Some-college    2
dtype: int64

sex     education
Female  9th             1
        Bachelors       2
        Masters         2
Male    11th            1
        Assoc-acdm      1
        Assoc-voc       1
        Bachelors       2
        HS-grad         2
        Some-college    2
dtype: int64

In [46]:
# Now it's ok

.........................................![image.png]()

In [47]:
Group_by_sex = data.groupby(['education','sex'])
print(type(Group_by_sex))
Group_by_sex.size()

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

education     sex
11th          Male      1
9th           Female    1
Assoc-acdm    Male      1
Assoc-voc     Male      1
Bachelors     Female    2
              Male      2
HS-grad       Male      2
Masters       Female    2
Some-college  Male      2
dtype: int64

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

education     sex
11th          Male      1
9th           Female    1
Assoc-acdm    Male      1
Assoc-voc     Male      1
Bachelors     Female    2
              Male      2
HS-grad       Male      2
Masters       Female    2
Some-college  Male      2
dtype: int64

In [ ]:
# As you can see, Group_by_education is not a DataFrame, it has a special format - DataFrameGroupBy.

# To create a new DataFrame from DataFrameGroupBy, you need to apply the method unstack().

![image.png]()

.........................................![image.png]()

In [49]:
Group_by_sex_DataFrame = Group_by_sex.size().unstack()
Group_by_sex_DataFrame

sex           Female  Male
education
11th             NaN   1.0
9th              1.0   NaN
Assoc-acdm       NaN   1.0
Assoc-voc        NaN   1.0
Bachelors        2.0   2.0
HS-grad          NaN   2.0
Masters          2.0   NaN
Some-college     NaN   2.0

sex           Female  Male
education
11th             NaN   1.0
9th              1.0   NaN
Assoc-acdm       NaN   1.0
Assoc-voc        NaN   1.0
Bachelors        2.0   2.0
HS-grad          NaN   2.0
Masters          2.0   NaN
Some-college     NaN   2.0

<html> <h3 style="color:blue;"> Data Transformation </h3> </html>

In [ ]:
# The apply() method allows you to apply custom functions to data

.........................................![image.png]()

In [51]:
df = pd.DataFrame({ 'A':[1,2], 'B': [10,20] })
df

   A   B
0  1  10
1  2  20

   A   B
0  1  10
1  2  20

.........................................![image.png]()

In [52]:
def custom_function(x):
  return x * 2
df['B'] = df['B'].apply(custom_function)
df

   A   B
0  1  20
1  2  40

   A   B
0  1  20
1  2  40

<html> <h3 style="color:blue;"> Pandas can read .csv or .html database from a webpage: </h3> </html>

In [ ]:
# This is a very useful feature for downloading financial and other data from websites on the Internet.

.........................................![image.png]()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [55]:

sid = '2463439'
last_digit = int(sid[-1])
n = 10 if last_digit == 0 else last_digit
print(f"The value of n is: {n}")

The value of n is: 9

In [57]:

Group_by_relationship_hours = data.groupby(["relationship", "hours-per-week"]).size()
print("\nGrouping by relationship and hours-per-week:")
print(Group_by_relationship_hours)

Grouping by relationship and hours-per-week:
relationship   hours-per-week
Husband        13.0              1
               40.0              2
               45.0              1
               80.0              1
Not-in-family  16.0              1
               40.0              2
               50.0              2
Own-child      30.0              1
Wife           40.0              2
dtype: int64

In [58]:

def reduce_hours(hours):
  return hours - n

data['reduced-hours-per-week'] = data['hours-per-week'].apply(reduce_hours)
print("\nDataFrame with reduced-hours-per-week column:")
display(data)

DataFrame with reduced-hours-per-week column:

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Answer,Workclass,IsHomeless,reduced-hours-per-week
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,NaN,40.0,United-States,<=50K,NaN,False,31.0
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K,NaN,False,4.0
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,NaN,40.0,United-States,<=50K,NaN,False,31.0
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,NaN,40.0,United-States,<=50K,NaN,False,31.0
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,NaN,40.0,Cuba,<=50K,NaN,False,31.0
5,37,Private,284582.0,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0.0,NaN,40.0,United-States,<=50K,NaN,False,31.0
6,49,Private,160187.0,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0.0,0.0,16.0,Jamaica,<=50K,NaN,False,7.0
7,52,Self-emp-not-inc,209642.0,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,45.0,United-States,>50K,NaN,False,36.0
8,31,Private,45781.0,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084.0,NaN,50.0,United-States,>50K,NaN,False,41.0
10,37,Private,280464.0,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0.0,NaN,80.0,United-States,>50K,NaN,False,71.0
12,23,Private,122272.0,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,Female,0.0,NaN,30.0,United-States,<=50K,NaN,False,21.0
13,32,Private,205019.0,Assoc-acdm,12.0,Never-married,Sales,Not-in-family,Black,Male,0.0,NaN,50.0,United-States,<=50K,NaN,False,41.0
14,40,Private,121772.0,Assoc-voc,11.0,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0.0,NaN,40.0,?,>50K,NaN,False,31.0
15,25,NaN,NaN,Some-college,NaN,NaN,NaN,NaN,White,Male,0.0,NaN,NaN,NaN,NaN,Private,True,NaN

In [59]:

Group_by_relationship_reduced_hours = data.groupby(["relationship", "reduced-hours-per-week"]).size()
print("\nGrouping by relationship and reduced-hours-per-week:")
print(Group_by_relationship_reduced_hours)

Grouping by relationship and reduced-hours-per-week:
relationship   reduced-hours-per-week
Husband        4.0                       1
               31.0                      2
               36.0                      1
               71.0                      1
Not-in-family  7.0                       1
               31.0                      2
               41.0                      2
Own-child      21.0                      1
Wife           31.0                      2
dtype: int64

# Lab Logbook Requirement:

<html> <h3 style="font-style:italic; color:blue;">
    
1) Determine a number (n) equal to the last digit of your SID. If the last digit of your SID is '0', then use 10.
2) Group by "relationship" and "hours-per-week". The first grouping should be by relationship.
3) Reduce all "hours-per-week" column values ​​in the original DataFrame by the value 'n'. Use a function.
4) Group ​​by "relationship" and the reduced "hours-per-week".
5) Add the code and result to your Lab Logbook.

<html> <h3 style="color:red;">
NOTE: DON'T FORGET TO SAVE AND BACK UP YOUR COMPLETED JUPYTER NOTEBOOK AND LAB LOGBOOK ON GITHUB OR ONEDRIVE.
</h3> </html>